### PR TITLE
release v2024.10.0

### PR DESCRIPTION
**Pull request by barbeque-squared**
see https://github.com/UltraStar-Deluxe/USDX/issues/912

### CODE REVIEW

**Comment by s09bQ5** [comment]
Was about to do the same.

How about updating the runtime to 24.08 while we're at it? Haven't tested it with that version yet, though.

**Comment by barbeque-squared** [comment]
PS who have write rights on this repo, and would it be possible to add me (and bohning so there's a backup) ? I'll still make PRs, which is also a lot less pain if I can just do them in this repo directly instead of having to sync a fork, push there, not forget to delete my branch, etc.

**Comment by barbeque-squared** [comment]
> Haven't tested it with that version yet, though.

I don't know enough about flathub to judge whether this is a good idea or not. If you're not sure, just do it after this has gone in?

**Comment by s09bQ5** [comment]
ok

**Comment by s09bQ5** [comment]
We need to update the shared-modules submodule first. I believe the build will be fixed by https://github.com/flathub/shared-modules/commit/b0e640fd5065b15ccb66e1db00c7cc531004ae4c.

**Comment by s09bQ5** [comment]
I think you need to rebase your branch to trigger a new test build.

**Comment by s09bQ5** [comment]
A quick test shows that it works (audio, video, camera, projectm).

**Pull request merged**
