### PR TITLE
Update manifest for v2024.5.1 release

### PR DESCRIPTION
**Pull request by finn-wa**
Release notes: https://github.com/UltraStar-Deluxe/USDX/releases/tag/v2024.5.1

### CODE REVIEW

**Comment by s09bQ5** [comment]
Finally someone else helping with this, but it looks like the AppStream linter has become more strict since December.

**Comment by finn-wa** [comment]
I suppose it would be better if the appstream changes I made were put in the USDX repository, but then we'd have to wait for the next release. I'll open a PR for that soon

**Comment by barbeque-squared** [comment]
I can't really test these (I don't use flatpak) and I don't know what the policy is before things can be merged here either. Not that I can, but I was halfway through making a PR for 2024.8.0 when I noticed this PR, guess I'll hold off on that PR for the time being...

**Comment by s09bQ5** [comment]
@barbeque-squared, I don't think it makes sense to merge this PR now that 2024.8.0 is so close and includes @finn-wa's appstream fixes.

**Comment by s09bQ5** [comment]
Superseded by #10.

**Comment by barbeque-squared** [comment]
thanks for clearing this up! I knew we also had some appstream things on the USDX side, but as you can tell it's not something I know all that much about.

(the release instructions on the USDX side are very helpful, I just got suspicious when this repo's master was still on 2023.12.0)

**Pull request closed without merging**
